//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: id.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Id_IdCreateCall: ClientCallUnary {}

fileprivate final class Id_IdCreateCallBase: ClientCallUnaryBase<Id_CreateRequest, Id_CreateResponse>, Id_IdCreateCall {
  override class var method: String { return "/id.Id/Create" }
}


/// Instantiate Id_IdServiceClient, then call methods of this protocol to make API calls.
internal protocol Id_IdService: ServiceClient {
  /// Synchronous. Unary.
  func create(_ request: Id_CreateRequest, metadata customMetadata: Metadata) throws -> Id_CreateResponse
  /// Asynchronous. Unary.
  func create(_ request: Id_CreateRequest, metadata customMetadata: Metadata, completion: @escaping (Id_CreateResponse?, CallResult) -> Void) throws -> Id_IdCreateCall

}

internal extension Id_IdService {
  /// Synchronous. Unary.
  func create(_ request: Id_CreateRequest) throws -> Id_CreateResponse {
    return try self.create(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  func create(_ request: Id_CreateRequest, completion: @escaping (Id_CreateResponse?, CallResult) -> Void) throws -> Id_IdCreateCall {
    return try self.create(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Id_IdServiceClient: ServiceClientBase, Id_IdService {
  /// Synchronous. Unary.
  internal func create(_ request: Id_CreateRequest, metadata customMetadata: Metadata) throws -> Id_CreateResponse {
    return try Id_IdCreateCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  internal func create(_ request: Id_CreateRequest, metadata customMetadata: Metadata, completion: @escaping (Id_CreateResponse?, CallResult) -> Void) throws -> Id_IdCreateCall {
    return try Id_IdCreateCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

