apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: id
  labels:
    app: id
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: id
  template:
    metadata:
      labels:
        app: id
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - id
              topologyKey: kubernetes.io/hostname
      containers:
        - name: id
          image: us.gcr.io/taeho-io-220708/id:${CIRCLE_SHA1}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:80"]
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:80"]
            initialDelaySeconds: 15

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: id-hpa
  labels:
    app: id
spec:
  scaleTargetRef:
    kind: Deployment
    name: id
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: v1
kind: Service
metadata:
  name: id
  labels:
    app: id
spec:
  ports:
    - port: 80
      name: grpc
  selector:
    app: id

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: id-route-public-grpc-no-auth
spec:
  hosts:
    - api.taeho.io
  gateways:
    - public-gateway
  http:
    - match:
        - uri:
            prefix: /id.Id/
      route:
        - destination:
            host: id
            port:
              number: 80
